---
- name: debian_family | Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest
    update_cache: yes

- name: debian_family | Add gpg key of Docker repository
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    validate_certs: False
  when: ansible_distribution_release != 'trusty'

- name: debian_family | Add gpg key of Docker repository
  command:
    bash -c "curl -s https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | apt-key add -"
  when: ansible_distribution_release == 'trusty'

- name: debian_family | Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: debian_family | Install Docker
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - python-docker
      - docker-compose
  notify:
    - start docker
